require 'simple/machine'
require 'simple/inspector'
require 'simple/number'
require 'simple/add'
require 'simple/multiply'
require 'simple/boolean'
require 'simple/less_than'
require 'simple/variable'
